### ISSUE TITLE
Add integrations between README and Actions

### ISSUE THREAD

**Issue by dtq-three** [DATATRONiQ/node-red-contrib-iiot-opcua#8]
- [x] Update build status placeholder badge for `build` action

- [x] Add a Test Status badge
  - [x] Add a `tests`action
  - [x] Display results in README badge

- [ ] Add a code quality badge to README
  - [ ] Integrate with CodeClimate?

a few more integrations to consider: https://github.com/moscajs/aedes

**Comment by ghost** [comment]
Except for the code quality badge, this has been handled as part of #10
